### ISSUE TITLE
Why the box_factor is set as 4 for replica dataset

### ISSUE THREAD

**Issue by licj15** [zhihao-lin/neurmips#3]
Dear Authors,

Thanks for the great work and the open sourced code!
When I am reading the code, I noticed that [box_factor is set as 4](https://github.com/zhihao-lin/neurmips/blob/main/configs/replica-room0.yaml#L30) for replica.
Although box_factor is not mentioned in the paper, but from its [corresponding code](https://github.com/zhihao-lin/neurmips/blob/7989595c095bd993ebce3fdc080f9b1c1c895b19/mnh/plane_geometry.py#L54-L55), I guess it is use to create a box with is box_factor times larger than the bounds of the points. 

However, if my understanding is correct, why not set it as 1.0 which best matches the fact that the walls for indoor scenes are exactly at the bounds of the points?

If my understanding is wrong, could you elaborate more about how you decide box_factor as 4? 
So that it may help to train on other scenes (e.g., scenes collected by other users from real world).

Thank you!

**Comment by chih-hao-lin** [comment]
Hi, thanks for your comment and question.
Your understanding of box_factor is correct, it makes a 6-face box which is box_factor times larger than the points boundary. 
Since there are some texture-less region in Replica dataset (e.g. white walls), the point cloud reconstructed by COLMAP might be incomplete, and box_factor=1 would not contain the full scene.
As a result, we set a slightly larger box_factor, which can also allow rendering from viewpoints in larger range. The number is decided through experiments.

**Comment by licj15** [comment]
Thank you for the detailed answer! 
It is very helpful!
